// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZSO4Gz9qeuhbzBotFCIti0eRU7IxdL1Q',
    appId: '1:682751805563:web:5f48ad46d8ce1a0973bade',
    messagingSenderId: '682751805563',
    projectId: 'jsnf-ecc86',
    authDomain: 'jsnf-ecc86.firebaseapp.com',
    storageBucket: 'jsnf-ecc86.firebasestorage.app',
    measurementId: 'G-5WZRMZ8FRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD90YrmLEDmFMdeQZ1pf7qKrv6ceC4ssdI',
    appId: '1:682751805563:android:9bff9f7227a9d92473bade',
    messagingSenderId: '682751805563',
    projectId: 'jsnf-ecc86',
    storageBucket: 'jsnf-ecc86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-MpzQXtmsK7t2jqxS8N3-GvBuSxkFs9o',
    appId: '1:682751805563:ios:4e20a82ca9af5eb573bade',
    messagingSenderId: '682751805563',
    projectId: 'jsnf-ecc86',
    storageBucket: 'jsnf-ecc86.firebasestorage.app',
    iosBundleId: 'com.example.storeMangment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-MpzQXtmsK7t2jqxS8N3-GvBuSxkFs9o',
    appId: '1:682751805563:ios:4e20a82ca9af5eb573bade',
    messagingSenderId: '682751805563',
    projectId: 'jsnf-ecc86',
    storageBucket: 'jsnf-ecc86.firebasestorage.app',
    iosBundleId: 'com.example.storeMangment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZSO4Gz9qeuhbzBotFCIti0eRU7IxdL1Q',
    appId: '1:682751805563:web:fa7f9bea8475a9d073bade',
    messagingSenderId: '682751805563',
    projectId: 'jsnf-ecc86',
    authDomain: 'jsnf-ecc86.firebaseapp.com',
    storageBucket: 'jsnf-ecc86.firebasestorage.app',
    measurementId: 'G-E8WNDGNGVD',
  );

}